server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.15.129
aliyun:
  sms:
    accessKeyId:
    accessKeySecret:
    template_code:
    sign_name: BiniCan
